"""MVP-2: driver_scores

Revision ID: 1ea46d45de96
Revises: 92b8b5038ecd
Create Date: 2026-06-14 19:46:49.484819

"""
from alembic import op
import sqlalchemy as sa


revision = '1ea46d45de96'
down_revision = '92b8b5038ecd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('period_from', sa.Date(), nullable=False),
    sa.Column('period_to', sa.Date(), nullable=False),
    sa.Column('points', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('breakdown', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_scores_driver_id'), 'driver_scores', ['driver_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_driver_scores_driver_id'), table_name='driver_scores')
    op.drop_table('driver_scores')
    # ### end Alembic commands ###
