"""MVP-3: incoming_messages, message_sources

Revision ID: 3da571c5ebdb
Revises: a31d3eb56d90
Create Date: 2026-06-14 20:33:03.611651

"""
from alembic import op
import sqlalchemy as sa


revision = '3da571c5ebdb'
down_revision = 'a31d3eb56d90'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('manual', 'import', 'telegram', 'sms', 'max', 'whatsapp', 'phone', name='source_type', native_enum=False), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incoming_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.Enum('manual', 'import', 'telegram', 'sms', 'max', 'whatsapp', 'phone', name='source_type', native_enum=False), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('external_id', sa.String(length=200), nullable=True),
    sa.Column('sender', sa.String(length=200), nullable=True),
    sa.Column('sender_name', sa.String(length=200), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('parsed', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('new', 'converted', 'ignored', name='incoming_status', native_enum=False), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['message_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incoming_messages_source_type'), 'incoming_messages', ['source_type'], unique=False)
    op.create_index(op.f('ix_incoming_messages_status'), 'incoming_messages', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incoming_messages_status'), table_name='incoming_messages')
    op.drop_index(op.f('ix_incoming_messages_source_type'), table_name='incoming_messages')
    op.drop_table('incoming_messages')
    op.drop_table('message_sources')
    # ### end Alembic commands ###
