"""MVP-3: widen source_type for google_sheets

Revision ID: 84694ee6dca1
Revises: 3da571c5ebdb
Create Date: 2026-06-14 20:48:35.994738

"""
from alembic import op
import sqlalchemy as sa


revision = '84694ee6dca1'
down_revision = '3da571c5ebdb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('incoming_messages', 'source_type',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('manual', 'import', 'telegram', 'sms', 'max', 'whatsapp', 'phone', 'google_sheets', name='source_type', native_enum=False, length=20),
               existing_nullable=False)
    op.alter_column('message_sources', 'type',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('manual', 'import', 'telegram', 'sms', 'max', 'whatsapp', 'phone', 'google_sheets', name='source_type', native_enum=False, length=20),
               existing_nullable=False)
    op.alter_column('orders', 'source_type',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('manual', 'import', 'telegram', 'sms', 'max', 'whatsapp', 'phone', 'google_sheets', name='source_type', native_enum=False, length=20),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'source_type',
               existing_type=sa.Enum('manual', 'import', 'telegram', 'sms', 'max', 'whatsapp', 'phone', 'google_sheets', name='source_type', native_enum=False, length=20),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)
    op.alter_column('message_sources', 'type',
               existing_type=sa.Enum('manual', 'import', 'telegram', 'sms', 'max', 'whatsapp', 'phone', 'google_sheets', name='source_type', native_enum=False, length=20),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)
    op.alter_column('incoming_messages', 'source_type',
               existing_type=sa.Enum('manual', 'import', 'telegram', 'sms', 'max', 'whatsapp', 'phone', 'google_sheets', name='source_type', native_enum=False, length=20),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)
    # ### end Alembic commands ###
