"""MVP-2: client merged_into_id (dedup)

Revision ID: 92b8b5038ecd
Revises: ef188d82414e
Create Date: 2026-06-14 19:24:12.029050

"""
from alembic import op
import sqlalchemy as sa


revision = '92b8b5038ecd'
down_revision = 'ef188d82414e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('merged_into_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_clients_merged_into_id'), 'clients', ['merged_into_id'], unique=False)
    op.create_foreign_key(None, 'clients', 'clients', ['merged_into_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_index(op.f('ix_clients_merged_into_id'), table_name='clients')
    op.drop_column('clients', 'merged_into_id')
    # ### end Alembic commands ###
