"""MVP-2: cash_handovers

Revision ID: a31d3eb56d90
Revises: 09c85d616d95
Create Date: 2026-06-14 20:22:24.735716

"""
from alembic import op
import sqlalchemy as sa


revision = 'a31d3eb56d90'
down_revision = '09c85d616d95'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_handovers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('handover_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('driver_id', 'handover_date', name='uq_cash_driver_date')
    )
    op.create_index(op.f('ix_cash_handovers_driver_id'), 'cash_handovers', ['driver_id'], unique=False)
    op.create_index(op.f('ix_cash_handovers_handover_date'), 'cash_handovers', ['handover_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cash_handovers_handover_date'), table_name='cash_handovers')
    op.drop_index(op.f('ix_cash_handovers_driver_id'), table_name='cash_handovers')
    op.drop_table('cash_handovers')
    # ### end Alembic commands ###
