"""MVP-3: products, order_items

Revision ID: eed70b0c1efe
Revises: 84694ee6dca1
Create Date: 2026-06-15 07:14:14.219039

"""
from alembic import op
import sqlalchemy as sa


revision = 'eed70b0c1efe'
down_revision = '84694ee6dca1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.Enum('bottle_pc', 'bottle_pet', 'pump', 'other', name='product_kind', native_enum=False, length=None), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.Enum('bottle_pc', 'bottle_pet', 'pump', 'other', name='product_kind', native_enum=False, length=None), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    # ### end Alembic commands ###

    # Каталог по умолчанию (3 базовых товара)
    op.execute(
        """
        INSERT INTO products (name, kind, unit_price, is_active, sort_order, created_at) VALUES
          ('Вода 19 л (поликарбонат)', 'bottle_pc', 300.00, true, 1, now()),
          ('Вода 19 л (ПЭТ)',          'bottle_pet', 250.00, true, 2, now()),
          ('Помпа',                    'pump',      1000.00, true, 3, now())
        """
    )
    # Бэкофилл order_items из фиксированных количеств существующих заказов.
    # Историческая цена позиции неизвестна — берём текущую из каталога
    # (order.total_amount остаётся источником истины по сумме заказа).
    for kind, qty_col in (
        ("bottle_pc", "bottles_pc_qty"),
        ("bottle_pet", "bottles_pet_qty"),
        ("pump", "pumps_qty"),
    ):
        op.execute(
            f"""
            INSERT INTO order_items
                (order_id, product_id, name, kind, qty, unit_price, amount, created_at)
            SELECT o.id, p.id, p.name, '{kind}', o.{qty_col},
                   p.unit_price, p.unit_price * o.{qty_col}, now()
            FROM orders o
            JOIN products p ON p.kind = '{kind}'
            WHERE o.{qty_col} > 0
            """
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_table('products')
    # ### end Alembic commands ###
