"""MVP-2: geocode_cache

Revision ID: ef188d82414e
Revises: 468cc1b13f24
Create Date: 2026-06-14 18:56:05.439224

"""
from alembic import op
import sqlalchemy as sa


revision = 'ef188d82414e'
down_revision = '468cc1b13f24'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geocode_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query_normalized', sa.Text(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('precision', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('normalized_address', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geocode_cache_query_normalized'), 'geocode_cache', ['query_normalized'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_geocode_cache_query_normalized'), table_name='geocode_cache')
    op.drop_table('geocode_cache')
    # ### end Alembic commands ###
